config/routes.rb
Rails.application.routes.draw do
  get '/overview' => 'overview#index'

  resources :categories
  resources :costs
  resources :incomes

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'categories#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category
end

app/controllers/costs_controller.rb
class CostsController < AuthenticatedController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
    @cost = Cost.find_by_id(params[:id])
  end

  # GET /costs/new
  def new
    @cost = Cost.new
    @categories = Category.all
  end

  # GET /costs/1/edit
  def edit
    @cost = Cost.find_by_id(params[:id])
    @categories = Category.all
  end

  # POST /costs
  # POST /costs.json
  def create
    # @cost = @categories.expenses.new(cost_params)
    @cost = Cost.new(cost_params) do |cost|
      cost.category = Category.find_by_id(params[:category])
    end

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully added.' }
        format.json { render :show, status: :created, location: @cost }
        format.js
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    @cost = Cost.update(cost_params) do |cost|
      cost.category = Category.find_by_id(params[:category])
    end

    respond_to do |format|
      if @cost.persisted?
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:amount, :category)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for @cost, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <%= select_tag "category", options_from_collection_for_select(@categories, "id", "name", @cost.try(:category).try(:id)) %>

  <div class="form-group">
    <%= f.label :amount, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :amount, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  costs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/costs/edit.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Cost %></h1>
</div>
<%= render :partial => 'form' %>

app/views/costs/index.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => Cost %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.id %></td>
        <td><%= cost.amount %></td>
        <td><%=l cost.created_at, format: :long %></td>
        <td>
          <%= link_to cost_path(cost), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to cost_path(cost), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cost_path,
            :class => 'btn btn-primary' %>

app/views/costs/new.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Cost %></h1>
</div>
<%= render :partial => 'form' %>

app/views/costs/show.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => Cost %></h1>
</div>

<h2>Category: <%= @cost.category.name %></h2>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:amount) %></dt>
      <dd><pre class="prettyprint"><%= @cost.amount %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              costs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cost_path(@cost), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cost_path(@cost),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>