config/routes.rb
Rails.application.routes.draw do
  get '/overview' => 'overview#index'

  resources :categories
  resources :costs
  resources :incomes

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'categories#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category


end

app/controllers/incomes_controller.rb
class IncomesController < AuthenticatedController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @categories = Category.find_by_id(params[:category_id])
    @income = @category.income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully added.' }
        format.json { render :show, status: :created, location: @income }
        format.js
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:amount)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for @income, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :amount, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :amount, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  incomes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<%- model_class = Income -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Income %></h1>
</div>
<%= render :partial => 'form' %>

app/views/incomes/index.html.erb
<%- model_class = Income -%>
<div class="page-header">
  <h1><%=t '.title', :default => Income %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.id %></td>
        <td><%= income.amount %></td>
        <td><%=l income.created_at, format: :long %></td>
        <td>
          <%= link_to income_path(income), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to income_path(income), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_income_path,
            :class => 'btn btn-primary' %>

app/views/incomes/new.html.erb
<%- model_class = Income -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Income %></h1>
</div>
<%= render :partial => 'form' %>

app/views/incomes/show.html.erb
<%- model_class = Income -%>
<div class="page-header">
  <h1><%=t '.title', :default => Income %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:amount) %></dt>
      <dd><pre class="prettyprint"><%= @income.amount %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              incomes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_income_path(@income), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              income_path(@income),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>